name: Bot de PetColinas
on:
  workflow_dispatch: # Esto activa el botón azul de "Run workflow"
  schedule:
    - cron: '15 13 * * *' # Publica a las 9:15 AM hora RD

jobs:
  publicar_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerias
        run: pip install requests
      - name: Ejecutar bot
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
        run: python main.py
