name: Publicación Diaria PetColinas
on:
  schedule:
    - cron: '15 13 * * *' # 9:15 AM AST (UTC-4)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar script
        run: python main.py
