name: Publicacion Diaria PetColinas
on:
  workflow_dispatch: # Esto nos permite darle al botón de "Play" manualmente
  schedule:
    - cron: '15 13 * * *' # 9:15 AM AST (UTC-4)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar script
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
        run: python main.py
